### ISSUE TITLE
Add instructions for running tests with Stack

### ISSUE THREAD

**Issue by killtheliterate** [exercism/xhaskell#140]
It seems that [stack](http://docs.haskellstack.org/en/stable/README/) is the recommended way to install Haskell these days. As a Haskell newbie, I haven't quite figured out how to run tests with `stack`, but that seems like a valuable addition to the README.

**Comment by killtheliterate** [comment]
Seems `stack runhaskell leap_test.hs` is halfway there.

**Comment by kytrinyx** [comment]
Ah, nice! When you figure it out, would you mind helping update the README?

Does the LeapYear module exist already, or did you fetch the exercise and is stack complaining because you still need to create it?

**Comment by killtheliterate** [comment]
Yeah, definitely. It may be that `cabal-install` ends up being the most appropriate way, outside of making each excercism problem a stack project.

**Comment by rbasso** [comment]
About using Stack

<br>
I have been thinking for a while about how to ease compiling and testing without demanding too much from a newcomer, but most people used the *Haskell Platform* and, without *Stack*, it would be to difficult to solve this problem.

Now that *Stack* is included in the new versions of the *Haskell Platform*, maybe it's time to think about making each exercise a *Stack project* as @killtheliterate mentioned. That would make people stop living *cabal hell* and allow better automated testing.

From the user's point of view, it would be enough to type `stack setup; stack test` to download, build everything and run the tests.

Of course, there are problems with that approach:

1. Needs *Stack*
2. Needs two additional project files, `stack.yaml` and `leap.cabal`.
3. Demands explicit package dependency, forcing the user to list any additional packages it uses in the solution in `leap.cabal`.
4. Needs at least a sub-folder to separate the tests from the user's code, so *cabal* can track dependencies correctly. It could also work without sub-folders, but then It gets messy when you try to add dependencies on packages.

We can solve (2) easily, using the following templates for **leap.cabal**

```
name:                   leap
version:                0.0.0.1
build-type:             Simple
cabal-version:          >=1.10

library
    hs-source-dirs:     src
    exposed-modules:    LeapYear
    build-depends:      base
    default-language:   Haskell2010
    ghc-options:        -Wall

test-suite leap-test
    type:               exitcode-stdio-1.0
    hs-source-dirs:     test
    main-is:            leap_test.hs
    build-depends:      leap
                      , base
                      , HUnit
    default-language:   Haskell2010
```
and for **stack.yaml**

```
resolver: lts-6.0
```

Using the same resolver in multiples exercises would save a lot of downloads for everyone.

The problem 3 - demanding explicit dependencies - is almost educational, but it would be nice to have some basic instructions on how to add them to `leap.cabal`.

I don't understand yet how the CLI works to know if problem 4 - having sub-folders - is really a problem.

The advantages would be:

- No errors due to different versions of software.
- Simple, independent, automated, easily reproducible tests for each problem.
- Forcing users to get acquainted with `cabal` and `stack`.

I still don't know if it would be good to put bounds for the package in `leap.cabal`, so that people could also use `cabal` directly instead of `stack`. That would be nice but decreases maintainability.

<br>
This is just an idea, but...

Are there any plan to leave the *Haskell Platform* behind in favor of *cabal* or *stack*?

**Comment by subshad** [comment]
Alternatively, would you be open to a pr with some docs on how to use stack as a global pkg manager with the exercism problems? I'm happy to take a shot at writing it today.

I ran into this earlier and am reasonably confident I have it setup and working without each problem needing to be its own stack project.

**Comment by killtheliterate** [comment]
I haven't been able to quite get it working. Got as far as `stack install HUnit`, and then `stack exec foo.hs` stops throwing errors about missing deps, but can't find the module under test.

It does seem excessive to make each problem a stack proj. As an end user, the only thing I really care about is not finding myself in "cabal hell" while just trying to learn. Looking forward to seeing what you've got working!

**Comment by rbasso** [comment]
I started using *Stack* with a big project including all my solutions, and It was just a little slow to do incremental compilation. The major problem, however, was that I had to keep in one `stack.yaml` the `extra-deps` for all the exercises, and I lost control of which dependencies corresponded to which exercises.

I agree it's perfectly possible to use a single project to manage all exercises @subshad - and I'm sure there is a lot of people that would benefit from instructions on how to do so -  but I don't think it's the best design to put together in a project unrelated code. In a smaller scale, this also creates a *intra-project* dependency hell with `extra-deps`, but that would not be a problem here.

In my opinion, a guide on how to install *Stack* and use it for a single exercise would be enough to introduce it, and a note about using it to manage a global project for all exercises would valuable too. :)

**Comment by rbasso** [comment]
I agree, @killtheliterate. It would be too disruptive to make each problem a *stack* project.

Right now I was thinking in the possibility of creating a *single exercise* as a *Stack* project,
to introduce it to people, but some more general changes would be needed to allow that, and I have no idea about what people would think about it.

To allow a *stack project* new kind of exercise the following files would require a complete rewriting:

- .travis.yml
- bin/check-exercises.hs

Maybe it's not worthy to change it if people are not having trouble compiling the sources...

**Comment by subshad** [comment]
@rbasso a how to use Stack for a single project seems like a great starting point. I honestly wasn't even suggesting that far. I was thinking just 

* how to install it
* how to install the required packages to your global config
* what and where to name your solution to the problem
* the command to run to test your solution

This approach would mean you don't have to bundle any of the stack specific code since it's essentially just being used as a cabal replacement, right? Is that worth documenting?

**Comment by rbasso** [comment]
Sorry! I got that wrong!

Never thought of using Stack's global project. I just use *cabal sandboxes* and *stack projects* here.

Now I'm curious about how you use it and why!

**Comment by subshad** [comment]
Honestly, in this case just because reorganising exercism/haskell to easily use Stack seemed like more of a pain than it was worth, but I don't have cabal-install installed and had Stack.

Aside from that, to allow the use of ghci with installed packages without needing to be in a project?

**Comment by rbasso** [comment]
Nice. Even without a project it seems better than the *Haskell Platform*.

```
$ stack setup
$ stack install HUnit
$ stack ghci
$ stack runghc leap_test
```

This is how am I supposed to use it?

*ps: Worked in Debian (jessie) / Failed in NixOS (unstable) because of reference to /bin/bash.*

**Comment by subshad** [comment]
yep, that's exactly what I did. Stable and easy. I'll write up a snippet for the Readme and open a PR later today?

**Comment by rbasso** [comment]
Sounds nice. FYI, I don't have access to the repository. :-)

**Comment by kytrinyx** [comment]
Hi, sorry. I've been onboarding in a new job, and haven't checked in all week :/ I would be so grateful for a PR on the README!

**Comment by subshad** [comment]
No worries, I'll draft something simple now :+1:

**Comment by rbasso** [comment]
Considering #147 was merged, This issue should be Closed, right?

**Comment by subshad** [comment]
I guess so? @killtheliterate were those instructions close to what you wanted?

**Comment by killtheliterate** [comment]
@subshad perfect! Thanks so much.
