### ISSUE TITLE
Exercises do not come with .cabal files

### ISSUE THREAD

**Issue by jack-trikeapps** [exercism/xhaskell#272]
Although the haskell exercises come with `package.yaml` files, they don't come with `.cabal` files, leading to this delightful initial experience if using an old version of `stack`:

```
$ exercism fetch haskell

Not Submitted: 1 problem
haskell (Leap) /home/endgame/exercism/haskell/leap

New:           1 problem
haskell (Leap) /home/endgame/exercism/haskell/leap

unchanged: 0, updated: 0, new: 1

endgame@cyberdwarf:/home/endgame/exercism$ cd haskell/leap/
endgame@cyberdwarf:/home/endgame/exercism/haskell/leap$ stack test
No .cabal file found in directory /home/endgame/exercism/haskell/leap/
```

It might be worth documenting this: a `stack upgrade` followed by a `hash -r` (or spawning a new shell) fixed the problem for me.

**Comment by rbasso** [comment]
Thank you very much for the feedback! :+1: 

> Although the haskell exercises come with package.yaml files, they don't come with .cabal files

As an alternative solution, you could use `hpack` to generate the `.cabal` file directly, which sometimes is useful if you want to play with cabal sandboxes, but I would not recommend that for normal usage.

> It might be worth documenting this: a stack upgrade followed by a hash -r (or spawning a new shell) fixed the problem for me.

I would like to avoid documenting stack's installation and troubleshooting directly in the track, because the instructions depend on the operating system and stack's site is usually better at explaining that. 

That said, we have to be more clear about the need of a recent Stack's version and maybe give some pointers on how to update it.

Right now I'm moving to another city and preparing for an international travel, so I don't know when I'll be able to fix `INSTALLATION.md` to include this information. But we'll definitely fix that. Thanks! :smile:

**Comment by jack-trikeapps** [comment]
Your reasoning is sound. I actually tried `hpack`initially, but it's not a viable workaround: the ghc versions that the nightly snapshots use are too recent for old versions of `stack`.

I think a good way to stop returning newbies from tripping up, while keeping the documentation maintainable and of a reasonable scope, would be to say something like "The exercises in this track require a reasonably recent version of `stack`. If you are getting errors not listed here, upgrade `stack` and try again."

Everything that the exercises need is in release versions of `stack`, so people won't need to upgrade to git versions or anything extreme. This feels like a good compromise to me.

**Comment by rbasso** [comment]
A recent case indicates that #279 was not enough to avoid people having *"No cabal file" problems.

I'm reopening this issue so that we don't forget to patch `docs/TESTS.md` and `SETUP.md` to include an explicit recommendation to upgrade stack if this error occurs.
