### ISSUE TITLE
anagram: Change tests to be order-insensitive

### ISSUE THREAD

**Issue by rbasso** [exercism/xhaskell#392]
A user [suggested](http://exercism.io/submissions/4e468e7ead3942d6af77c64149e18b61) that we could change `anagram`'s test suite to check the output list ignoring the word's order.

The way it is now, `anagramsFor word` must behave as `filter p` to pass the tests.

The patch would be really simple,

```bash
sed -i 's/shouldBe/shouldMatchList/g' test/Tests.hs
```

... but first we have to decide if it is important to check the output order.

Does anyone have an opinion on this?

**Comment by petertseng** [comment]
Strangely, I had never thought of this. Probably many other languages check the same ordering too!

It seems OK to use `shouldMatchList`, if all we are asking in the problem is "which of these words are anagrams?"

I am sure there are various arguments for why it makes sense to keep the output in the same order as the input (and my implementations will probably keep it so) but I don't think it is *essential to the problem* that it has to be that way.

**Comment by rbasso** [comment]
Agreed! The order doesn't seems to be an essential part of the problem.

I marked this issue as a *good first patch* to see if any new contributor is willing to open a PR.

**Comment by abo64** [comment]
I agree, too. Have the test suite as general as possible to allow for as many solutions as possible. In the end we want to explore those possible solutions for the maximum learning effect and not be arbitrarily restricted.
