### ISSUE TITLE
Investigate track health and status of the track

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xhaskell#437]
I've used Sarah Sharp's [FOSS Heartbeat](https://github.com/sarahsharp/foss-heartbeat) project to generate stats for each of the language track repositories, as well as the x-common repository.

The Exercism heartbeat data is published here: https://exercism.github.io/heartbeat/

When looking at the data, please disregard any activity from me (`kytrinyx`), as I would like to get the language tracks to a point where they are entirely maintained by the community.

Please take a look at the heartbeat data for this track, and answer the following questions:

* To what degree is the track maintained?
* Who (if anyone) is merging pull requests?
* Who (if anyone) is reviewing pull requests?
* Is there someone who is not merging pull requests, but who comments on issues and pull requests, has thoughtful feedback, and is generally helpful? If so, maybe we can invite them to be a maintainer on the track.

I've made up the following scale:

* **ORPHANED** - Nobody (other than me) has merged anything in the past year.
* **ENDANGERED** - Somewhere between ORPHANED and AT RISK.
* **AT RISK** - Two people (other than me) are actively discussing issues and reviewing and merging pull requests.
* **MAINTAINED** - Three or more people (other than me) are actively discussing issues and reviewing and merging pull requests.

It would also be useful to know if there a lot of activity on the track, or just the occasional issue or comment.

Please report the current status of the track, including your best guess on the above scale, back to the top-level issue in the discussions repository: https://github.com/exercism/discussions/issues/97

**Comment by petertseng** [comment]
What's changed in our status in the past year+?

November 2016: https://github.com/exercism/discussions/issues/97#issuecomment-261912117

> * Two active maintainers.
> * Sporadic contributions from non-maintainers.
> * No frequent contributor to receive write access yet.
> * Still under active reformulation: 579 commits in the last year.

Now:

Back at one maintainer.

I can't give this track a lot of my time. I initiate changes to bring it up to date with problem-specifications but I don't initiate other changes. I review others' PRs *eventually* but sometimes it takes me days or weeks to do it.

**Comment by kytrinyx** [comment]
I appreciate the update @petertseng. I am hoping that once we get v2 launched I'll be able to focus on recruiting maintainers for all the tracks.

**Comment by petertseng** [comment]
I'm ill suited to being a sole maintainer of any Exercism track (the current state), because the person who I am today has no interest in:

* designing a sensible curriculum
    * in exercism v1: what order should the exercises go in? what difficulty should they have?
    * in exercism v2: how should the tree structure look like?
* most of the exercises present in any given track

With every exercise that gets added, the above tasks become harder, especially since now there's one more exercise to watch for changes to canonical-data.json and description.md in the problem-specifications repo.

Because of my other priorities in life, for at least two months (and probably longer) I cannot change who I am to become interested in these points.

I once considered myself a "break glass in case of emergency"-only maintainer. I'd advise that we should go back to thinking of me in that manner. I suppose that since there are no other maintainers it is sort of an emergency, but we should acknowledge that it is the case.

**Comment by kytrinyx** [comment]
@petertseng this is perfectly reasonable, and very useful to know.

I'm working on a GitHub integration right now that will make it easier for us all to have a "break glass in case of emergency approach" where it makes sense, and to clearly distinguish for each track what the current state is. I'm hoping to have a usable integration in the next week or two.
