### ISSUE TITLE
readme: "Contributing" link points to x-api contributing guide

### ISSUE THREAD

**Issue by rbasso** [exercism/xhaskell#456]
The `README.md` files has a link to a `contributing guide` pointing to https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md.

This seems inappropriate - my fault - and it should probably link to another place.

Where?

**Comment by abo64** [comment]
Probably https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md ?
Seems like the most up to date file to me, and I wanted to link to it also in other places.

**Comment by abo64** [comment]
Fine. I will change the link in my PR #450 .

**Comment by rbasso** [comment]
Closed by #456

**Comment by petertseng** [comment]
> This seems inappropriate - my fault - and it should probably link to another place.

Wasn't your fault. I just had to fix this for a few other tracks too.

In https://github.com/exercism/x-common/pull/125 (2015 November), the x-common CONTRIBUTING guide was created.

After that, the x-api contributing guide was gutted in https://github.com/exercism/x-api/commit/a157350c6c9025314be8fbbaf82b90810bd9204e

This means that it doesn't really make sense to link to the x-api contributing guide anymore - it has very little relevant information for contributing to this track.

Much later (2016 October) the template for a new track repository was updated so that they link to the x-common CONTRIBUTING guide too, not x-api: https://github.com/exercism/x-template/commit/5f9143266d05b29317638f45f1cabaccb860e6ca

So all that happened here is that we link to a file that used to be good, but didn't change it when it was no longer good.
