### ISSUE TITLE
Verify contents and format of track documentation

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xhaskell#458]
Each language track has documentation in the `docs/` directory, which gets included on the site
on each track-specific set of pages under [/languages](http://exercism.io/languages).

We've added some general guidelines about how we'd like the track to be documented in exercism/exercism.io#3315
which can be found at https://github.com/exercism/exercism.io/blob/master/docs/writing-track-documentation.md

Please take a moment to look through the documentation about documentation, and make sure that
the track is following these guidelines. Pay particularly close attention to **how to use images**
in the markdown files.

Lastly, if you find that the guidelines are confusing or missing important details, then a pull request
would be greatly appreciated.

**Comment by petertseng** [comment]
This language track has these docs:

* How to install: https://github.com/exercism/xhaskell/blob/master/docs/INSTALLATION.md, appearing at http://exercism.io/languages/haskell/installing.
  * One question I have here - we explain how to install Stack, and in #187 this replaced the instructions of installing the Haskell Platform.
  * It does seem that Stack will manage installing GHC for the student. Am I correct in my understanding? If not, we need to change this. Can you confirm @rbasso?
  * Why don't I answer this question myself? Because on my machines I have a GHC installed in ways other than Stack, so I don't know.
* How to install dependences: We explain how to install Stack, which will take care of all other dependencies.
* How to run the tests: https://github.com/exercism/xhaskell/blob/master/docs/TESTS.md, appearing at http://exercism.io/languages/haskell/tests
* Introduction: https://github.com/exercism/xhaskell/blob/master/docs/ABOUT.md, appearing at http://exercism.io/languages/haskell/about
* Where learn: https://github.com/exercism/xhaskell/blob/master/docs/LEARNING.md, appearing at http://exercism.io/languages/haskell/learning
* Resources: https://github.com/exercism/xhaskell/blob/master/docs/RESOURCES.md, appearing at http://exercism.io/languages/haskell/resources

Finally, we have no images in any of the docs in the `docs` directory (we do have images in our README.md, but those are not displayed on the website).

Given the above information, I claim that this track meets the basic requirements set out in this issue.

Of course, anyone reading is free to help us improve our documentation. The above assertion that we meet the basic requirements doesn't necessarily mean that all the docs are perfect and never need changes again.

**Comment by petertseng** [comment]
EBWODP: Clarify: the image in our README is just the Travis CI icon, no other image. I copied a bit too much of this comment from another track =D

**Comment by rbasso** [comment]
> It does seem that Stack will manage installing GHC for the student. Am I correct in my understanding? If not, we need to change this. Can you confirm @rbasso?

Stack will use the system's GHC is it has the correct version, otherwise it will ask the user to install the required version running `stack setup`, as we explain in [TESTS.md](https://github.com/exercism/xhaskell/blob/8c073a98a5cee65e60d84e83aed4f8696bb696b4/docs/TESTS.md).

I decided to put the explanation about it in `TESTS.md` instead of `INSTALLATION.md` because the user may need to run it again if we update the exercises to use a new GHC, and at the time I considered this as different from a initial setup.
