### ISSUE TITLE
word-count: Removed test case

### ISSUE THREAD

**Issue by behrtam** [exercism/xhaskell#501]
After some discussion we adopted one of your test cases `symbols are separators` (https://github.com/exercism/xpython/pull/177) because only splitting on white space was seen as to easy. Now I saw that you removed that test case in #232 when you switched from HUnit to hspec.

Any specific reason why you dropped that test case or did you just take what was part of the x-common json at that time?

**Comment by rbasso** [comment]
I guess I just used what was in `x-common`, because it was easier and also to comply with it (the Haskell track was too "unique" at the time), but I also think that tests should not be too prescriptive.

It this particular case, I'm not sure if it makes the exercise more interesting. The core of the problem is counting things, while the accessory problem is extracting the words from a string.

With it the exercise is a little harder. Without it people have a little more freedom.

**Comment by petertseng** [comment]
https://github.com/exercism/xrust/issues/196 also did not like the test.

Neither in that track did we have a specific reason for removing it, other than x-common.

**Comment by petertseng** [comment]
The test was added in https://github.com/exercism/exercism.io/pull/650.

**Comment by behrtam** [comment]
Okay, than I will probably remove that test from the python track as well to be consistent.
