### ISSUE TITLE
Gigasecond Improvement

### ISSUE THREAD

**Issue by lpalma** [exercism/xhaskell#503]
While working on Gigasecond exercise, as part of #473, I noticed two things:

1. The exercise is not documented in [the exercises page](http://exercism.io/languages/haskell/exercises);
1. The function name `fromDay` may be confusing for beginners since it doesn't take a _day_, but rather a `UTCTime`. What about simply `from` or `fromUtcTime` ?

Perhaps this repository is not responsible for **1** and it should be raised in [exercism.io](https://github.com/exercism/exercism.io) instead?

**Comment by petertseng** [comment]
> The exercise is not documented in the exercises page;

Because it is [deprecated in this repo](https://github.com/exercism/xhaskell/pull/280), and deprecated exercises intentionally do not show up in the list.

> The function name `fromDay` may be confusing for beginners since it doesn't take a _day_, but rather a `UTCTime`. What about simply `from` or `fromUtcTime` ?

Sure, either seems reasonable. I guess it was called `fromDay` because despite taking in a `UTCTime`, the time always had the hour/minute/second set to zero, but that is caused by the tests, not the function - the function would reasonably be able to accept any `UTCTime`, not just those at 00:00:00

**Comment by petertseng** [comment]
Do we want to cover deprecated exercises too as part of #473?

**Comment by lpalma** [comment]
I think this can be closed now following https://github.com/exercism/xhaskell/issues/473#issuecomment-285916374
