### ISSUE TITLE
Override probot/stale defaults, if necessary

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xhaskell#515]
Per the discussion in https://github.com/exercism/discussions/issues/128 we
will be installing the probot/stale integration on the Exercism organization on
April 10th, 2017.

By default, probot will comment on issues that are older than 60 days, warning
that they are stale. If there is no movement in 7 days, the bot will close the issue.
By default, anything with the labels `security` or `pinned` will not be closed by
probot.

If you wish to override these settings, create a .github/stale.yml file as described
in https://github.com/probot/stale#usage, and make sure that it is merged
before April 10th.

If the defaults are fine for this repository, then there is nothing further to do.
You may close this issue.

**Comment by petertseng** [comment]
It is at this point that I wish I had the time to use https://developer.github.com/v3/issues/comments/ to get some data on this: Which issues would have been auto-closed by probot, with a 60-day strategy? Should they have been closed?

What do I mean by "should", even? Well, it seems to me that there are various kinds of issues:

* Issues where we've decided on a clear plan of action
  * Good examples: the [good first patch issues](https://github.com/exercism/xhaskell/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20label%3A%22good%20first%20patch%22%20).
  * These issues should probably stay open until the action is taken, no matter how stale they get.
  * Only exception probably is if they get so stale that the action they recommend is no longer relevant to the repo, but the bot does not have the ability to decide that, so I say the bot should **never** close these issues.
  * For these issues, the bot forces extra work on us, by forcing us to apply a label to exempt it.
* Issues where there isn't a clear plan of action, perhaps discussions or questions.
  * Good examples... ??? I don't have one for the Haskell track right now.
  * For these it seems being stale implies not enough consensus to change the status quo and/or the querent is no longer interested in the question.
  * For these issues, the bot saves us work.

If the bot creates more work than it saves, then I would obviously oppose having it. Since I don't have that data right now, I'll defer my vote. Feel free to proceed and make a decision without having my vote.

**Comment by petertseng** [comment]
I'm finally ready to look at the data.

I used https://gist.github.com/petertseng/04edd07d4b35cda2cbc1d8142b6fcc13 to get a rough idea of the issues that would have been closed by this integration. (Limitations: It doesn't look at pull requests, and it may have false positives for issues that are edited after they are closed)

In this track's history, 25/124 issues went stale (I deliberately do not include a # in front of each since I don't mean to reference those issues from this one):

```
470 Document periodic maintenance tasks (Stack snapshot update, cache clear)
469 Changes to Luhn tests
455 space-age: Typo in HINTS.md
452 discussion: Test cases about memory and/or performance: Should we have them?
442 stack.yaml: Avoiding multiplicity
416 Ensuring we are up to date with x-common
398 readme: Fix instructions for running the tests.
397 Allow marking an example as should-fail
274 Update config.json to match new specification
211 tests: Tracking migration to hspec with fail-fast.
130 travis: All GHCs use same cache; check whether that's OK
129 travis: Automatically invalidate caches if new package versions exist
125 clock: canonical test data has been improved
124 travis: Document why we test the GHC versions that we do
122 check-exercises.hs redundant import warning after GHC 7.10.x
119 travis: all builds install all GHC versions, rather than just the one they're testing
117 travis: 7.10.1 -> 7.10.3?
116 robot-simulator: "turning edge cases" are not necessarily edge cases
115 discussion: Should we return Maybe when there is a possibility of invalid input?
111 binary: improve tests for invalid numbers
 99 Verify "Largest Series Product" exercise implementation
 92 pov: Consider making tests insensitive to child ordering
 88 Move exercises to subdirectory
 85 Gigasecond - Could not find module ‘System.Locale’
 59 Binary search tree cannot be a monoid
```

Of these, I would say 88, 92, 99, 111, 116, 117, 119, 122, 124, 125, 129, 274, 397, 398, 455, 470 at least had clear enough calls to action that it seems like it doesn't make sense to close them even if they go stale. Then, 211 was known to be a long-term issue. So in 17 cases the bot would have caused extra work for the maintainers of this track and in only 8 cases the bot can save work.

As I promised, if the bot would create more work than it saves, I would oppose having it. So here is my vote in opposition.

**Comment by kytrinyx** [comment]
Agreed. I think that in this track we've been really good about making issues actionable, so the bot doesn't make sense.

**Comment by petertseng** [comment]
Hi. Guess nobody else wants to weigh in. Well, if there's one vote in opposition (mine) and no other votes, I suppose that means no bot, which is obviously fine with me. Let us know if that should change.
