### ISSUE TITLE
parallel-letter-frequency needs more hints and/or a benchmark

### ISSUE THREAD

**Issue by unmanbearpig** [exercism/xhaskell#519]
It's a great exercise but it's not clear how to check if your code is actually running in parallel. I've tried many things but haven't been able to make it run faster than sequentially even with larger input data. Here is my solution with a comment on some things I've tried http://exercism.io/submissions/1a8dcc995b1a4f0daedbacde58339a8e

I've looked through other solutions and found that other people have a similar problem, for example:

http://exercism.io/submissions/4bcec0f0062c481c966276bea1f453d7
> I'm not really clear on whether this is actually doing any worthwhile parallelization; any comments or general advice would be greatly appreciated

http://exercism.io/submissions/a8d66d748e64465b84205ddef94fa5ad
> This is a totally naive implementation of the parallelism requested, and it certainly slows things down on the test suite. But the test suite is so small I'm not sure if that's because I've parallelized badly or because parallelism isn't really called for here.

There is also a discussion in this solution http://exercism.io/submissions/ca2721207a1849ec8ee8d74e2de2c46e

So the main problems I see with it are:
 - Not clear how to test if it runs faster or if it runs in parallel at all.
 - Do you have to provide extra flags to the compiler or your binary to make it run in parallel? How to do it with Stack and hpack?
 - If my code utilizes multiple cores but in the end runs slower than sequentially, is it my fault or is it just the exercise is too small or can't be parallelized efficiently?

I'd love to help to improve this exercise but I need some hints on how to run and test it.

**Comment by petertseng** [comment]
Those interested in this issue and the track maintainers may find useful resources in https://github.com/exercism/xrust/pull/244 and https://github.com/exercism/xrust/pull/245 which added benchmarks to parallel-letter-frequency.. Main suggestion from there would have been to examine the effect of input size on which of the two is faster.

**Comment by petertseng** [comment]
Those interested in this issue and the track maintainers may find useful resources in https://github.com/exercism/xrust/pull/244 and https://github.com/exercism/xrust/pull/245 which added benchmarks to parallel-letter-frequency.

Main suggestion from there would have been to examine the effect of input size on which of the two is faster.

**Comment by rbasso** [comment]
Hi, @unmanbearpig!

> Not clear how to test if it runs faster or if it runs in parallel at all.

I'm also not sure about how to test if it runs in parallel.

To test speed, I guess that [criterion](http://www.serpentine.com/criterion/) is the most used library.

> Do you have to provide extra flags to the compiler or your binary to make it run in parallel? How to do it with Stack and hpack?

I don't know if you need special flags , but I think it makes sense to use at least `-O2` in anything performance related. You can use `ghc-options` and `ghc-prof-options` in your `package.yaml`, when using [hpack](https://github.com/sol/hpack).

> If my code utilizes multiple cores but in the end runs slower than sequentially, is it my fault or is it just the exercise is too small or can't be parallelized efficiently?

Some parallelizations are not worthy, but I don't know how to tell them apart beforehand. 😄

> I'd love to help to improve this exercise but...

Nice to hear that. 😄 

I really know little about the subject, but I'm considering adding benchmarks to some of the exercises since #182.

You may want to take a look at this [simple benchmark suite](https://github.com/rbasso/xhaskell/commit/14a91d6925e59d6f963265359a27bb187f103357) that I wrote for `leap`. It is easy and dumb, but it shows how to integrate benchmarks in the exercises, which you can run easily with `stack bench` or...

```
stack bench --benchmark-arguments="--output=index.html"
```

... if you want a *really beautiful* HTML output.

Here are the reasons why I didn't add benchmark suites in `xhaskell` yet:

- Most of the exercises don't really need them.
- I think that students shouldn't worry about performance until they face a real problem that demands it. The time spent grasping the type-classes seems way more productive IMHO.
- Performance tuning is an arcane topic in Haskell, so I don't think it is reasonable to expect beginners to deal with that so early.
- Haskell is non-strict, but sometimes I'm really lazy 😁 . Benchmarks would add maintenance, so I was looking for an exercise where the work clearly pays-off.

If we decide that this exercise deserves a benchmark suite, we would need to:

- Write a benchmark suite.
- Check that it correctly measures performance.
- Check whether parallelization increases performance.
- Check that the benchmarks compile against the stubs and solutions in Travis-CI.
- Add benchmark support in our Travis-CI scripts.
- Check if the increased compilation time in Travis-CI is acceptable (`criterion` has a lot of dependencies).
- Completely rewrite `HINTS.md` explaining how to measure performance.

I'm currently studying topics that are unrelated to this, so I don't know when/if I'll take the time to do it, so I'll just mark it as `waiting-for-pr`.

We'll be able to evaluate the pros/cons better with a concrete proposal.

---

Just to make things easier for anyone that decides to tackle this, here are some links:

- [Haskell Wiki - Performance](https://wiki.haskell.org/Performance)
- [A criterion tutorial](http://www.serpentine.com/criterion/tutorial.html)
- [Parallel and Concurrent Programming in Haskell - Simon Marlow](http://community.haskell.org/~simonmar/pcph/)

**Comment by unmanbearpig** [comment]
Thanks @rbasso, it's really helpful! I'm going to play with it and hopefully come up with something soon-ish.
