### ISSUE TITLE
Unable to run leap exercise tests

### ISSUE THREAD

**Issue by kevgathuku** [exercism/xhaskell#520]
Hi everyone, 
I'm having an issue running the tests for the second exercise, `Leap in Haskell`. 
I've followed the instructions in the [Installing Haskell](http://exercism.io/languages/haskell/installing) and [Running the Tests](http://exercism.io/languages/haskell/tests) sections.

The error I'm getting when I run `stack test` is:
```
leap-0.0.0: build (lib + test)
Preprocessing library leap-0.0.0...
Preprocessing test suite 'test' for leap-0.0.0...
Linking .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/test/test ...
Undefined symbols for architecture x86_64:
  "_timezm1zi6zi0zi1_DataziTimeziClockziCTimespec_getCTimespec1_closure", referenced from:
      _S18rU_srt in libHShspec-core-2.4.1-6tkqmeyrVhr6d0P1sYC06o.a(Runner.o)
      _SGsi_srt in libHShspec-core-2.4.1-6tkqmeyrVhr6d0P1sYC06o.a(Internal.o)
      _SigH_srt in libHSrandom-1.1-9tceXaeYIMZ4JrKq20Egog.a(Random.o)
      _Sj6y_srt in libHStf-random-0.5-BGjMgO8m67W8CHiEl15kZ7.a(Init.o)
      _S4as_srt in libHShspec-core-2.4.1-6tkqmeyrVhr6d0P1sYC06o.a(Timer.o)
  "_timezm1zi6zi0zi1_DataziTimeziClockziCTimespec_getCTimespec1_info", referenced from:
      _s18fj_info in libHShspec-core-2.4.1-6tkqmeyrVhr6d0P1sYC06o.a(Runner.o)
      _hspeczmcorezm2zi4zi1zm6tkqmeyrVhr6d0P1sYC06o_TestziHspecziCoreziFormattersziInternal_interpret16_info in libHShspec-core-2.4.1-6tkqmeyrVhr6d0P1sYC06o.a(Internal.o)
      _hspeczmcorezm2zi4zi1zm6tkqmeyrVhr6d0P1sYC06o_TestziHspecziCoreziFormattersziInternal_runFormatM1_info in libHShspec-core-2.4.1-6tkqmeyrVhr6d0P1sYC06o.a(Internal.o)
      _cikh_info in libHSrandom-1.1-9tceXaeYIMZ4JrKq20Egog.a(Random.o)
      _tfzmrandomzm0zi5zmBGjMgO8m67W8CHiEl15kZZ7_SystemziRandomziTFziInit_mkSeedTime1_info in libHStf-random-0.5-BGjMgO8m67W8CHiEl15kZ7.a(Init.o)
      _tfzmrandomzm0zi5zmBGjMgO8m67W8CHiEl15kZZ7_SystemziRandomziTFziInit_initTFGen1_info in libHStf-random-0.5-BGjMgO8m67W8CHiEl15kZ7.a(Init.o)
      _cjlB_info in libHStf-random-0.5-BGjMgO8m67W8CHiEl15kZ7.a(Init.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`gcc' failed in phase `Linker'. (Exit code: 1)
Progress: 1/2
--  While building package leap-0.0.0 using:
      /Users/kevin/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.2.0 build lib:leap test:test --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

`stack --version` returns:
```
Version 1.4.0 x86_64
```

I have tried everything I can at this point and I have no idea what else to try. Any help would be really appreciated.

**Comment by petertseng** [comment]
I got out my OS X test machine (it's currently 10.12.4) so as to be able to test with the most similar environment. There too my `stack --version` says "1.4.0 x86_64"

I ran with `-v` and saw that the command used was (other than the path to `.stack`) exactly the same.

```
2017-05-02 08:11:23.932658: [info] Linking .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/test/test ...
@(Stack/Build/Execute.hs:1070:67)
2017-05-02 08:11:24.520424: [debug] Process finished in 2157ms: /Users/pt/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.2.0 build lib:leap test:test --ghc-options " -ddump-hi -ddump-to-file"
```

We have eliminated a few differences but unfortunately I was not able to reproduce yet. A few more things I would try: 

* https://github.com/hspec/hspec-example is a very minimal hspec project. I was able to `git clone https://github.com/hspec/hspec-example`, change the `stack.yaml` to use `resolver: lts-8.2` (the same as the one used by `leap`), then `stack test` (tests pass). This would probably fail in the same way for you, but if it succeeds it implies the problem is specific to Exercism.
* Since clang had failed, it may be useful to see whether our versions are different and whether it explains anything. My `clang --version` says


```
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

In case it matters (since clang is provided by Xcode, right? I'm not very familiar with how Xcode works), my `xcodebuild -version` says:

```
Xcode 8.2.1
Build version 8C1002
```

If any values differ, let's see what happens if they are made the same.

**Comment by kevgathuku** [comment]
Hey @petertseng thanks for taking your time to investigate this 😄 
Downloading the  repository, changing the `stack.yaml` file and running `stack test` gives me the same error:
```
strip-0.0.0: build (lib + test)
Preprocessing library strip-0.0.0...
Preprocessing test suite 'spec' for strip-0.0.0...
Linking .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/spec/spec ...
Undefined symbols for architecture x86_64:
  "_timezm1zi6zi0zi1_DataziTimeziClockziCTimespec_getCTimespec1_closure", referenced from:
      _S18rU_srt in libHShspec-core-2.4.1-6tkqmeyrVhr6d0P1sYC06o.a(Runner.o)
      _SGsi_srt in libHShspec-core-2.4.1-6tkqmeyrVhr6d0P1sYC06o.a(Internal.o)
      _SigH_srt in libHSrandom-1.1-9tceXaeYIMZ4JrKq20Egog.a(Random.o)
      _Sj6y_srt in libHStf-random-0.5-BGjMgO8m67W8CHiEl15kZ7.a(Init.o)
      _S4as_srt in libHShspec-core-2.4.1-6tkqmeyrVhr6d0P1sYC06o.a(Timer.o)
  "_timezm1zi6zi0zi1_DataziTimeziClockziCTimespec_getCTimespec1_info", referenced from:
      _s18fj_info in libHShspec-core-2.4.1-6tkqmeyrVhr6d0P1sYC06o.a(Runner.o)
      _hspeczmcorezm2zi4zi1zm6tkqmeyrVhr6d0P1sYC06o_TestziHspecziCoreziFormattersziInternal_interpret16_info in libHShspec-core-2.4.1-6tkqmeyrVhr6d0P1sYC06o.a(Internal.o)
      _hspeczmcorezm2zi4zi1zm6tkqmeyrVhr6d0P1sYC06o_TestziHspecziCoreziFormattersziInternal_runFormatM1_info in libHShspec-core-2.4.1-6tkqmeyrVhr6d0P1sYC06o.a(Internal.o)
      _cikh_info in libHSrandom-1.1-9tceXaeYIMZ4JrKq20Egog.a(Random.o)
      _tfzmrandomzm0zi5zmBGjMgO8m67W8CHiEl15kZZ7_SystemziRandomziTFziInit_mkSeedTime1_info in libHStf-random-0.5-BGjMgO8m67W8CHiEl15kZ7.a(Init.o)
      _tfzmrandomzm0zi5zmBGjMgO8m67W8CHiEl15kZZ7_SystemziRandomziTFziInit_initTFGen1_info in libHStf-random-0.5-BGjMgO8m67W8CHiEl15kZ7.a(Init.o)
      _cjlB_info in libHStf-random-0.5-BGjMgO8m67W8CHiEl15kZ7.a(Init.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`gcc' failed in phase `Linker'. (Exit code: 1)
Progress: 1/2
--  While building package strip-0.0.0 using:
      /Users/kevin/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.2.0 build lib:strip test:spec --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```
My OSX version is also 10.12.4
`xcodebuild -version` gives me:
```
Xcode 8.3.2
Build version 8E2002
```
and here's the output I get from running `clang --version`
```
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
I'm not exactly sure how to make the version numbers the same, since my system seems to have later versions of the software. 
My guess is I am missing something from my system, but I just can't figure out what it is 🤔

**Comment by petertseng** [comment]
> my system seems to have later versions of the software.

Oops, obviously that probably means **I'm** out of date and I should try to update my test machine. As you can see, since it's only used for testing I don't always do the best job of keeping it up to date... I can try to do that and report back.

In the meantime, I used my preferred search engine to look for the error message and found https://github.com/haskell/time/issues/64 and https://github.com/snoyberg/http-client/issues/260 and maybe some ideas in there can help - the ideas are (progressively bigger hammers) to add `--with-ghc=$(which ghc)` to the `stack test` command, or to remove the `.stack-work` directory, or to remove `~/.stack/snapshots`

**Comment by kevgathuku** [comment]
The largest hammer worked 😄 
I ran `rm -rf ~/.stack/snapshots` and the `stack test` command worked like a charm.
Thanks a lot for your help. Really appreciated @petertseng  👍
