### ISSUE TITLE
Total functions in nucleotide exercise.

### ISSUE THREAD

**Issue by joneshf** [exercism/xhaskell#73]
`count` and `nulceotideCounts` are intended to be partial functions. Why not make them total? Either with a simplistic `Maybe Int`/`Maybe (Map Char Int)` or a more descriptive data type that contains information about the error.

Perhaps something like:
```haskell
data NucleotideError = Invalid Char

count :: Char -> String -> Either NucleotideError Int
nucleotideCounts :: String -> Either NucleotideError (Map Char Int)
```

**Comment by etrepum** [comment]
That sounds like a great idea for a pull request! Please feel free to submit one.

Ultimately the most flexible approach would be to have an error type that included the invalid Char, the state up to that point, and the rest of the input such that it could be resumed if the caller decided the best strategy was to discard invalid inputs. Given this approach, the public interface should be expanded to include accessor functions for that error type and a way to resume, e.g. `nucleotideCounts :: Map Char Int -> String -> Map Char Int`. Something simpler would be fine though, and still be a net improvement over what we have now.

Either is really the right call for this, since there is more information to give than pass/fail.
